//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TfsCheckoutNotification.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TfsCheckoutNotification.App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error with TFS Checkout Notification and it needs to be closed. \r\n\r\nContact the author to notify him about the problem. There&apos;s a new Event Log entry that may help..
        /// </summary>
        internal static string Common_UnexpectedException {
            get {
                return ResourceManager.GetString("Common_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string Configuration_IntervalHour {
            get {
                return ResourceManager.GetString("Configuration_IntervalHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval value must be an integer..
        /// </summary>
        internal static string Configuration_IntervalInteger {
            get {
                return ResourceManager.GetString("Configuration_IntervalInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string Configuration_IntervalMinute {
            get {
                return ResourceManager.GetString("Configuration_IntervalMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the interval type..
        /// </summary>
        internal static string Configuration_IntervalType {
            get {
                return ResourceManager.GetString("Configuration_IntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set an interval..
        /// </summary>
        internal static string Configuration_SetInterval {
            get {
                return ResourceManager.GetString("Configuration_SetInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} pending change(s)..
        /// </summary>
        internal static string Main_CountPendingChanges {
            get {
                return ResourceManager.GetString("Main_CountPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting to your Team Foundation Service. Check your connection..
        /// </summary>
        internal static string Main_ErrorConnectTFS {
            get {
                return ResourceManager.GetString("Main_ErrorConnectTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Main_ErrorTitle {
            get {
                return ResourceManager.GetString("Main_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no pending changes..
        /// </summary>
        internal static string Main_NoPendingChanges {
            get {
                return ResourceManager.GetString("Main_NoPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the collection to monitor..
        /// </summary>
        internal static string Main_SpecifyCollection {
            get {
                return ResourceManager.GetString("Main_SpecifyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in made by TFS Checkout Notification.
        /// </summary>
        internal static string PendingChange_CheckInComment {
            get {
                return ResourceManager.GetString("PendingChange_CheckInComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string PendingChange_ConfirmationTitle {
            get {
                return ResourceManager.GetString("PendingChange_ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking in your changes:\r\n\r\n {0}.
        /// </summary>
        internal static string PendingChange_ErrorCheckingIn {
            get {
                return ResourceManager.GetString("PendingChange_ErrorCheckingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error commiting changes.
        /// </summary>
        internal static string PendingChange_ErrorCheckingInTitle {
            get {
                return ResourceManager.GetString("PendingChange_ErrorCheckingInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error undoing your changes: \r\n\r\n{0}.
        /// </summary>
        internal static string PendingChange_ErrorUndoing {
            get {
                return ResourceManager.GetString("PendingChange_ErrorUndoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to undo all the selected items?.
        /// </summary>
        internal static string PendingChange_UndoConfirmation {
            get {
                return ResourceManager.GetString("PendingChange_UndoConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your {0} pending changes are here:.
        /// </summary>
        internal static string PendingChanges_AllYourPendingChanges {
            get {
                return ResourceManager.GetString("PendingChanges_AllYourPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pending changes will appear here:.
        /// </summary>
        internal static string PendingChanges_AllYourPendingChangesEmpty {
            get {
                return ResourceManager.GetString("PendingChanges_AllYourPendingChangesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to check in all the selected items?\r\n\r\nIf there&apos;s a check in policy for any of these pending changes, it will be overwritten..
        /// </summary>
        internal static string PendingChanges_CheckInConfirmation {
            get {
                return ResourceManager.GetString("PendingChanges_CheckInConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the app information. Closing....
        /// </summary>
        internal static string PendingChanges_ErrorLoadingInfo {
            get {
                return ResourceManager.GetString("PendingChanges_ErrorLoadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error undoing changes.
        /// </summary>
        internal static string PendingChanges_ErrorUndoingTitle {
            get {
                return ResourceManager.GetString("PendingChanges_ErrorUndoingTitle", resourceCulture);
            }
        }
    }
}
